# Generated by: python manage.py export_position_group_seed
# Copy DEPARTMENTS / POSITIONS / MAPPINGS into seed_positions.py when needed.

DEPARTMENTS = [
    [
        "BGD",
        "Ban giám đốc",
        null,
        1
    ],
    [
        "KD",
        "Phòng Kinh doanh",
        null,
        2
    ],
    [
        "NS",
        "Phòng Nhân sự",
        null,
        3
    ],
    [
        "LS",
        "Khoa Lâm sàng",
        null,
        4
    ],
    [
        "XN",
        "Khoa Xét nghiệm",
        null,
        5
    ],
    [
        "DD",
        "Phòng Điều dưỡng",
        null,
        6
    ],
    [
        "CDHA",
        "Khoa Chẩn đoán hình ảnh",
        null,
        7
    ],
    [
        "VH",
        "Phòng Vận hành",
        null,
        8
    ],
    [
        "KT",
        "Phòng Kế toán",
        null,
        9
    ],
    [
        "CNTT",
        "Phòng Công nghệ thông tin",
        null,
        10
    ],
    [
        "CSKH",
        "Phòng Chăm sóc khách hàng",
        null,
        11
    ]
]

POSITIONS = [
    [
        "GD",
        "Giám đốc",
        "BGD",
        9
    ],
    [
        "PGD",
        "Phó giám đốc",
        "BGD",
        7
    ],
    [
        "TPKD",
        "Trưởng phòng kinh doanh",
        "KD",
        5
    ],
    [
        "NVKD",
        "Nhân viên kinh doanh",
        "KD",
        1
    ],
    [
        "TPNS",
        "Trưởng phòng nhân sự",
        "NS",
        5
    ],
    [
        "NVNS",
        "Nhân viên Nhân sự",
        "NS",
        1
    ],
    [
        "DDT",
        "Điều dưỡng trưởng",
        "LS",
        5
    ],
    [
        "GDYK",
        "Giám đốc Y khoa",
        "LS",
        5
    ],
    [
        "BSDALIEU",
        "Bác sĩ Da liễu",
        "LS",
        1
    ],
    [
        "BSGMHS",
        "Bác sĩ Gây mê hồi sức",
        "LS",
        1
    ],
    [
        "BSMAT",
        "Bác sĩ Mắt",
        "LS",
        1
    ],
    [
        "BSNOI",
        "Bác sĩ Nội",
        "LS",
        1
    ],
    [
        "BSNOISOI",
        "Bác sĩ Nội soi",
        "LS",
        1
    ],
    [
        "BSNGOAI",
        "Bác sĩ Ngoại",
        "LS",
        1
    ],
    [
        "BSRHM",
        "Bác sĩ Răng Hàm Mặt",
        "LS",
        1
    ],
    [
        "BSSAN",
        "Bác sĩ Sản",
        "LS",
        1
    ],
    [
        "BSTMH",
        "Bác sĩ Tai Mũi Họng",
        "LS",
        1
    ],
    [
        "TPXN",
        "Trưởng phòng xét nghiệm",
        "XN",
        5
    ],
    [
        "KTVXN",
        "Kỹ thuật viên xét nghiệm",
        "XN",
        1
    ],
    [
        "TPDD",
        "Trưởng phòng điều dưỡng",
        "DD",
        5
    ],
    [
        "DD",
        "Điều dưỡng",
        "DD",
        1
    ],
    [
        "TPCDHA",
        "Trưởng khoa CĐHA",
        "CDHA",
        5
    ],
    [
        "KTVCDHA",
        "Kỹ thuật viên CĐHA",
        "CDHA",
        1
    ],
    [
        "TPVH",
        "Trưởng phòng vận hành",
        "VH",
        5
    ],
    [
        "TKYK",
        "Thư ký y khoa",
        "VH",
        1
    ],
    [
        "KTTRUONG",
        "Kế toán trưởng",
        "KT",
        5
    ],
    [
        "KTVIEN",
        "Kế toán viên",
        "KT",
        1
    ],
    [
        "TPCNTT",
        "Trưởng phòng CNTT",
        "CNTT",
        5
    ],
    [
        "NVCNTT",
        "Nhân viên CNTT",
        "CNTT",
        1
    ]
]

MAPPINGS = [
    [
        "BSDALIEU",
        [
            "Doctors"
        ]
    ],
    [
        "BSGMHS",
        [
            "Doctors"
        ]
    ],
    [
        "BSMAT",
        [
            "Doctors"
        ]
    ],
    [
        "BSNOI",
        [
            "Doctors"
        ]
    ],
    [
        "BSNOISOI",
        [
            "Doctors"
        ]
    ],
    [
        "BSNGOAI",
        [
            "Doctors"
        ]
    ],
    [
        "BSRHM",
        [
            "Doctors"
        ]
    ],
    [
        "BSSAN",
        [
            "Doctors"
        ]
    ],
    [
        "BSTMH",
        [
            "Doctors"
        ]
    ],
    [
        "DD",
        [
            "Nurses"
        ]
    ],
    [
        "DDT",
        [
            "Managers",
            "Nurses"
        ]
    ],
    [
        "GD",
        [
            "Executives"
        ]
    ],
    [
        "GDYK",
        [
            "Doctors",
            "Managers"
        ]
    ],
    [
        "KTTRUONG",
        [
            "Accountants",
            "Managers"
        ]
    ],
    [
        "KTVCDHA",
        [
            "Imaging Technicians"
        ]
    ],
    [
        "KTVIEN",
        [
            "Accountants"
        ]
    ],
    [
        "KTVXN",
        [
            "Lab Technicians"
        ]
    ],
    [
        "NVCNTT",
        [
            "IT Staff"
        ]
    ],
    [
        "NVKD",
        [
            "Sales Team"
        ]
    ],
    [
        "NVNS",
        [
            "HR Admins"
        ]
    ],
    [
        "PGD",
        [
            "Executives",
            "Managers"
        ]
    ],
    [
        "TKYK",
        [
            "Operations Team"
        ]
    ],
    [
        "TPCDHA",
        [
            "Imaging Technicians",
            "Managers"
        ]
    ],
    [
        "TPCNTT",
        [
            "IT Staff",
            "Managers"
        ]
    ],
    [
        "TPDD",
        [
            "Managers",
            "Nurses"
        ]
    ],
    [
        "TPKD",
        [
            "Managers",
            "Sales Team"
        ]
    ],
    [
        "TPNS",
        [
            "HR Admins",
            "Managers"
        ]
    ],
    [
        "TPVH",
        [
            "Managers",
            "Operations Team"
        ]
    ],
    [
        "TPXN",
        [
            "Lab Technicians",
            "Managers"
        ]
    ]
]
