# Generated by Django 5.2 on 2026-04-03 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestarget',
            options={'ordering': ['-year', 'period_type', 'period_number'], 'verbose_name': 'KPI Sale', 'verbose_name_plural': 'KPI Sale'},
        ),
        migrations.AlterModelOptions(
            name='targetnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ghi chú KPI'},
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='period_number',
            field=models.PositiveSmallIntegerField(help_text='1-12 (tháng) / 1-4 (quý) / 1 (năm)'),
        ),
        migrations.AlterField(
            model_name='salestarget',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Để trống = target tổng team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL, verbose_name='Sale phụ trách'),
        ),
        migrations.AlterField(
            model_name='targetnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
