# Generated by Django 5.2 on 2026-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_fix_commitment_task_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingsignature',
            name='doc_hash',
            field=models.CharField(max_length=64, verbose_name='SHA-256 hash biên bản'),
        ),
    ]
