# Generated by Django 5.2 on 2026-04-04 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['stage_order', '-priority', 'due_date'], 'verbose_name': 'Công việc', 'verbose_name_plural': 'Công việc'},
        ),
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch sử công việc'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Bình luận'},
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_stage_c451a2_idx',
            old_name='tasks_stage_order_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_3b91a8_idx',
            old_name='tasks_assignee_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_bce847_idx',
            old_name='tasks_due_date_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Giờ thực tế'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận việc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn hoàn thành'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Giờ ước tính'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], db_index=True, default='MEDIUM', max_length=8, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang thực hiện'), ('IN_REVIEW', 'Chờ kiểm tra'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], db_index=True, default='TODO', max_length=15, verbose_name='Giai đoạn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Thứ tự trong giai đoạn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tags (ngăn cách bằng dấu phẩy)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='tasks_watching', to=settings.AUTH_USER_MODEL, verbose_name='Người theo dõi'),
        ),
        migrations.AlterField(
            model_name='taskactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='body',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Ghi chú nội bộ'),
        ),
    ]
