# Generated by Django 5.2 on 2026-04-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='hrm_employe_status_25a0ba_idx',
            old_name='hrm_employee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='hrm_employe_departm_0b83cd_idx',
            old_name='hrm_employee_dept_idx',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(help_text='Tự sinh hoặc nhập theo quy tắc nội bộ. VD: NV-2024-001', max_length=20, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = nhân viên, 5 = trưởng phòng, 9 = giám đốc', verbose_name='Cấp bậc'),
        ),
        migrations.AlterField(
            model_name='positiongroupmapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
