# Generated by Django 5.2 on 2026-04-06 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_rename_hrm_employee_status_idx_hrm_employe_status_25a0ba_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='Luôn là thứ Hai của tuần tương ứng.', verbose_name='Ngày đầu tuần (Thứ Hai)')),
                ('schedule_json', models.JSONField(blank=True, default=dict, help_text='{"mon": "morning", "tue": "all_day", "wed": null, ...}', verbose_name='Lịch theo ngày')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='hrm.employee', verbose_name='Bác sĩ')),
            ],
            options={
                'verbose_name': 'Lịch làm việc bác sĩ',
                'verbose_name_plural': 'Lịch làm việc bác sĩ',
                'db_table': 'hrm_doctor_schedule',
                'ordering': ['-week_start', 'doctor__full_name'],
                'indexes': [models.Index(fields=['week_start'], name='hrm_doc_sched_week_idx')],
                'unique_together': {('doctor', 'week_start')},
            },
        ),
    ]
