from __future__ import annotations

import json
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from apps.hrm.models import Department, Position, PositionGroupMapping


class Command(BaseCommand):
    help = (
        "Đọc Department / Position / PositionGroupMapping từ DB hiện tại "
        "và xuất ra seed dùng để cập nhật nhanh cho server thật."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--format",
            choices=("python", "json"),
            default="python",
            help="Định dạng file export. Mặc định: python",
        )
        parser.add_argument(
            "--output",
            type=str,
            default="tmp/hrm_position_group_seed.py",
            help=(
                "Đường dẫn file output. "
                "Mặc định: tmp/hrm_position_group_seed.py"
            ),
        )
        parser.add_argument(
            "--stdout",
            action="store_true",
            default=False,
            help="In seed ra stdout thay vì ghi file.",
        )

    def handle(self, *args, **options):
        output_format = options["format"]
        output_path = options["output"]
        write_stdout = options["stdout"]

        departments = self._build_departments()
        positions = self._build_positions()
        mappings = self._build_mappings()

        payload = {
            "departments": departments,
            "positions": positions,
            "mappings": mappings,
        }

        rendered = (
            self._render_python(payload)
            if output_format == "python"
            else self._render_json(payload)
        )

        if write_stdout:
            self.stdout.write(rendered)
            return

        target = Path(output_path)
        if not target.is_absolute():
            target = Path.cwd() / target

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")

        self.stdout.write(
            self.style.SUCCESS(
                f"Đã export seed: {target}\n"
                f"- Departments: {len(departments)}\n"
                f"- Positions: {len(positions)}\n"
                f"- Mappings: {len(mappings)}"
            )
        )

    @staticmethod
    def _build_departments() -> list[list[object]]:
        rows = []
        qs = Department.objects.select_related("parent").order_by("display_order", "name", "id")
        for department in qs:
            if not department.code:
                raise CommandError(
                    f"Department '{department.name}' chưa có code, không thể export seed ổn định."
                )
            parent_code = department.parent.code if department.parent else None
            rows.append([
                department.code,
                department.name,
                parent_code,
                department.display_order,
            ])
        return rows

    @staticmethod
    def _build_positions() -> list[list[object]]:
        rows = []
        qs = Position.objects.select_related("department").order_by("department__display_order", "-level", "name", "id")
        for position in qs:
            if not position.code:
                raise CommandError(
                    f"Position '{position.name}' chưa có code, không thể export seed ổn định."
                )
            department_code = position.department.code if position.department else None
            rows.append([
                position.code,
                position.name,
                department_code,
                position.level,
            ])
        return rows

    @staticmethod
    def _build_mappings() -> list[list[object]]:
        grouped: dict[str, list[str]] = {}
        qs = (
            PositionGroupMapping.objects
            .select_related("position", "django_group")
            .order_by("position__code", "django_group__name", "id")
        )
        for mapping in qs:
            if not mapping.position.code:
                raise CommandError(
                    f"Position '{mapping.position.name}' chưa có code, không thể export mapping."
                )
            grouped.setdefault(mapping.position.code, []).append(mapping.django_group.name)

        return [[position_code, group_names] for position_code, group_names in grouped.items()]

    @staticmethod
    def _render_python(payload: dict[str, list[list[object]]]) -> str:
        header = (
            "# Generated by: python manage.py export_position_group_seed\n"
            "# Copy DEPARTMENTS / POSITIONS / MAPPINGS into seed_positions.py when needed.\n\n"
        )
        body = (
            f"DEPARTMENTS = {json.dumps(payload['departments'], ensure_ascii=False, indent=4)}\n\n"
            f"POSITIONS = {json.dumps(payload['positions'], ensure_ascii=False, indent=4)}\n\n"
            f"MAPPINGS = {json.dumps(payload['mappings'], ensure_ascii=False, indent=4)}\n"
        )
        return header + body

    @staticmethod
    def _render_json(payload: dict[str, list[list[object]]]) -> str:
        return json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
