import pytest
from django.urls import reverse


ROUTE_CASES = [
    "authentication:patient_login",
    "authentication:staff_login",
    "dashboard:overview",
    "approvals:inbox",
    "approvals:my_requests",
    "organizations:company_list",
    "organizations:company_create",
    "catalogs:category_list",
    "catalogs:package_list",
    "catalogs:package_create",
    "contract:contract_list",
    "contract:quotation_list",
    "contract:create_proposal",
    "contract:corporate_contract_list",
    "contract:create_corporate_contract",
    "contract:implementation_plan_list",
    "scheduling:schedule_table",
    "scheduling:general_settings",
    "scheduling:register_schedule",
    "reception:checkin_tool",
    "reception:ajax_lookup",
    "reception:ajax_action",
    "reception:ajax_stats",
    "clinical:clinical_dashboard",
    "clinical:sum_assistant",
    "clinical:dental_exam_form",
    "clinical:pathology",
    "notifications:unread_count",
    "hrm:employee_list",
    "hrm:employee_create",
    "hrm:department_list",
    "hrm:position_list",
    "hrm:doctor_schedule_list",
    "hrm:work_schedule_month",
    "hrm:work_schedule_log",
    "analytics:overview",
    "analytics:service_stats",
    "targets:dashboard",
    "targets:create",
    "retention:overview",
    "retention:at_risk",
    "meeting:session_list",
    "meeting:session_create",
    "tasks:board",
    "tasks:create",
    "engagement:inbox",
    "engagement:contact_list_index",
    "engagement:settings",
    "procedures:list",
    "procedures:create",
    "media_library:index",
    "media_library:upload",
    "ai_assistant:index",
    "ai_assistant:new",
    "helpdesk:list",
    "helpdesk:create",
    "booking:register_schedule",
    "booking:appointment",
    "quality:incident_report_list",
    "quality:incident_report_public",
    "api_his:api_playground",
]


@pytest.mark.smoke
@pytest.mark.parametrize("route_name", ROUTE_CASES)
def test_named_routes_reverse_successfully(route_name):
    path = reverse(route_name)
    assert path.startswith("/")
