# Generated by Django 5.2 on 2026-04-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinrecord',
            name='exam_date',
            field=models.DateField(db_index=True, help_text='Ngày khách hàng thực sự đến khám (không phải khung lịch).', verbose_name='Ngày khám thực tế'),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
