import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(name="ConversationTag", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("name", models.CharField(max_length=50, unique=True)),
            ("color", models.CharField(max_length=7, default="#6c757d")),
        ], options={"db_table": "care_conversation_tag", "ordering": ["name"]}),
        migrations.CreateModel(name="ContactList", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("name", models.CharField(max_length=255)),
            ("description", models.TextField(blank=True)),
            ("status", models.CharField(max_length=12, choices=[("DRAFT","Nháp"),("ACTIVE","Đang chạy"),("PAUSED","Tạm dừng"),("COMPLETED","Hoàn thành"),("ARCHIVED","Lưu trữ")], default="DRAFT", db_index=True)),
            ("source_file", models.FileField(upload_to="engagement/uploads/", blank=True, null=True)),
            ("campaign_tag", models.CharField(max_length=100, blank=True)),
            ("allow_full_phone_groups", models.JSONField(default=list)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("assigned_to", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_lists_assigned", to=settings.AUTH_USER_MODEL)),
            ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_lists_created", to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "care_contact_list", "ordering": ["-created_at"]}),
        migrations.CreateModel(name="Contact", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("status", models.CharField(max_length=20, choices=[("NEW","Mới"),("ASSIGNED","Đã phân công"),("CALLING","Đang liên hệ"),("REACHED","Đã liên hệ được"),("NOT_REACHED","Không liên hệ được"),("INTERESTED","Quan tâm"),("NOT_INTERESTED","Không quan tâm"),("FOLLOW_UP","Cần theo dõi"),("CONVERTED","Đã chốt"),("DO_NOT_CALL","Không gọi lại")], default="NEW", db_index=True)),
            ("full_name", models.CharField(max_length=255)),
            ("phone_raw", models.CharField(max_length=20, db_index=True)),
            ("email", models.EmailField(blank=True)),
            ("company_name", models.CharField(max_length=255, blank=True)),
            ("position", models.CharField(max_length=100, blank=True)),
            ("address", models.TextField(blank=True)),
            ("extra_data", models.JSONField(default=dict, blank=True)),
            ("row_number", models.PositiveIntegerField(default=0)),
            ("last_call_at", models.DateTimeField(null=True, blank=True)),
            ("follow_up_at", models.DateTimeField(null=True, blank=True)),
            ("call_count", models.PositiveIntegerField(default=0)),
            ("note", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("contact_list", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="engagement.contactlist")),
            ("assigned_to", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_contacts_assigned", to=settings.AUTH_USER_MODEL)),
            ("linked_company", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_contacts", to="organizations.company")),
        ], options={"db_table": "care_contact", "ordering": ["row_number"]}),
        migrations.CreateModel(name="CallLog", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("channel", models.CharField(max_length=12, choices=[("PHONE","Điện thoại"),("ZALO","Zalo"),("MESSENGER","Messenger"),("EMAIL","Email"),("OTHER","Khác")], default="PHONE")),
            ("outcome", models.CharField(max_length=20)),
            ("duration_s", models.PositiveIntegerField(default=0)),
            ("note", models.TextField(blank=True)),
            ("follow_up_at", models.DateTimeField(null=True, blank=True)),
            ("called_at", models.DateTimeField(auto_now_add=True)),
            ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_logs", to="engagement.contact")),
            ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_call_logs", to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "care_call_log", "ordering": ["-called_at"]}),
        migrations.CreateModel(name="ChannelConfig", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("name", models.CharField(max_length=100)),
            ("channel_type", models.CharField(max_length=12, choices=[("ZALO","Zalo OA"),("MESSENGER","Facebook Messenger"),("WEBCHAT","Website Chat Widget"),("EMAIL","Email")], db_index=True)),
            ("status", models.CharField(max_length=10, choices=[("ACTIVE","Hoạt động"),("INACTIVE","Tắt"),("ERROR","Lỗi")], default="INACTIVE")),
            ("avatar_url", models.URLField(blank=True)),
            ("description", models.CharField(max_length=255, blank=True)),
            ("zalo_oa_id", models.CharField(max_length=100, blank=True)),
            ("zalo_access_token", models.TextField(blank=True)),
            ("zalo_refresh_token", models.TextField(blank=True)),
            ("zalo_secret_key", models.CharField(max_length=255, blank=True)),
            ("zalo_webhook_token", models.CharField(max_length=255, blank=True)),
            ("fb_page_id", models.CharField(max_length=100, blank=True)),
            ("fb_page_access_token", models.TextField(blank=True)),
            ("fb_app_secret", models.CharField(max_length=255, blank=True)),
            ("fb_verify_token", models.CharField(max_length=255, blank=True)),
            ("fb_app_id", models.CharField(max_length=100, blank=True)),
            ("webchat_widget_key", models.UUIDField(default=uuid.uuid4, unique=True)),
            ("webchat_allowed_origins", models.TextField(blank=True)),
            ("webchat_greeting", models.CharField(max_length=255, blank=True, default="Xin chào!")),
            ("webchat_offline_message", models.CharField(max_length=255, blank=True, default="Chúng tôi đang offline.")),
            ("webchat_theme_color", models.CharField(max_length=7, default="#1a5276")),
            ("webchat_position", models.CharField(max_length=12, default="bottom-right")),
            ("auto_reply_enabled", models.BooleanField(default=False)),
            ("auto_reply_text", models.TextField(blank=True)),
            ("business_hours_start", models.TimeField(null=True, blank=True)),
            ("business_hours_end", models.TimeField(null=True, blank=True)),
            ("email_address", models.EmailField(blank=True)),
            ("email_imap_host", models.CharField(max_length=100, blank=True)),
            ("email_imap_port", models.PositiveIntegerField(default=993)),
            ("email_smtp_host", models.CharField(max_length=100, blank=True)),
            ("email_smtp_port", models.PositiveIntegerField(default=587)),
            ("email_username", models.CharField(max_length=100, blank=True)),
            ("email_password", models.TextField(blank=True)),
            ("email_use_tls", models.BooleanField(default=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "care_channel_config", "ordering": ["channel_type","name"]}),
        migrations.CreateModel(name="Conversation", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ("status", models.CharField(max_length=10, choices=[("OPEN","Đang mở"),("PENDING","Chờ phản hồi"),("RESOLVED","Đã giải quyết"),("SNOOZED","Tạm ẩn")], default="OPEN", db_index=True)),
            ("priority", models.CharField(max_length=8, choices=[("LOW","Thấp"),("MEDIUM","Trung bình"),("HIGH","Cao"),("URGENT","Khẩn cấp")], default="MEDIUM")),
            ("external_id", models.CharField(max_length=255, db_index=True)),
            ("customer_name", models.CharField(max_length=255, blank=True)),
            ("customer_avatar", models.URLField(blank=True)),
            ("customer_platform_data", models.JSONField(default=dict, blank=True)),
            ("subject", models.CharField(max_length=255, blank=True)),
            ("internal_note", models.TextField(blank=True)),
            ("first_reply_at", models.DateTimeField(null=True, blank=True)),
            ("resolved_at", models.DateTimeField(null=True, blank=True)),
            ("snoozed_until", models.DateTimeField(null=True, blank=True)),
            ("last_message_at", models.DateTimeField(null=True, blank=True, db_index=True)),
            ("csat_score", models.PositiveSmallIntegerField(null=True, blank=True)),
            ("csat_comment", models.TextField(blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="engagement.channelconfig")),
            ("assigned_to", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_conversations", to=settings.AUTH_USER_MODEL)),
            ("linked_contact", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="conversations", to="engagement.contact")),
            ("linked_company", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_conversations", to="organizations.company")),
            ("tags", models.ManyToManyField(blank=True, related_name="conversations", to="engagement.conversationtag")),
        ], options={"db_table": "care_conversation", "ordering": ["-last_message_at","-created_at"]}),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["channel","external_id"], name="engagement_conv_ch_ext_idx")),
        migrations.AddIndex(model_name="conversation", index=models.Index(fields=["status","assigned_to"], name="engagement_conv_st_ag_idx")),
        migrations.CreateModel(name="Message", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("direction", models.CharField(max_length=3, choices=[("IN","Đến"),("OUT","Đi")], db_index=True)),
            ("msg_type", models.CharField(max_length=10, choices=[("TEXT","Văn bản"),("IMAGE","Hình ảnh"),("FILE","File"),("STICKER","Sticker"),("AUDIO","Audio"),("VIDEO","Video"),("TEMPLATE","Template"),("EVENT","Sự kiện")], default="TEXT")),
            ("content", models.TextField(blank=True)),
            ("attachments", models.JSONField(default=list, blank=True)),
            ("external_msg_id", models.CharField(max_length=255, blank=True, db_index=True)),
            ("is_read", models.BooleanField(default=False, db_index=True)),
            ("is_internal", models.BooleanField(default=False)),
            ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="engagement.conversation")),
            ("sender_agent", models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name="engagement_messages_sent", to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "care_message", "ordering": ["sent_at"]}),
        migrations.CreateModel(name="CannedResponse", fields=[
            ("id", models.BigAutoField(primary_key=True)),
            ("title", models.CharField(max_length=100)),
            ("shortcut", models.CharField(max_length=30, unique=True)),
            ("content", models.TextField()),
            ("channel_types", models.JSONField(default=list, blank=True)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
        ], options={"db_table": "care_canned_response", "ordering": ["title"]}),
    ]
