# Generated by Django 5.2 on 2026-04-04 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-called_at'], 'verbose_name': 'Lịch sử liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='cannedresponse',
            options={'ordering': ['title'], 'verbose_name': 'Mẫu phản hồi nhanh'},
        ),
        migrations.AlterModelOptions(
            name='channelconfig',
            options={'ordering': ['channel_type', 'name'], 'verbose_name': 'Kênh tích hợp'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['row_number'], 'verbose_name': 'Liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danh sách liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at', '-created_at'], 'verbose_name': 'Hội thoại'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at'], 'verbose_name': 'Tin nhắn'},
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='care_conver_channel_683420_idx',
            old_name='engagement_conv_ch_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='care_conver_status_64fa94_idx',
            old_name='engagement_conv_st_ag_idx',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration_s',
            field=models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hẹn follow-up'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú cuộc gọi'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='outcome',
            field=models.CharField(choices=[('NO_ANSWER', 'Không bắt máy'), ('BUSY', 'Máy bận'), ('WRONG_NUMBER', 'Sai số'), ('REACHED', 'Liên hệ được'), ('INTERESTED', 'Quan tâm'), ('NOT_INTERESTED', 'Không quan tâm'), ('CALLBACK', 'Hẹn gọi lại'), ('CONVERTED', 'Đã chốt'), ('DO_NOT_CALL', 'Yêu cầu không gọi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='channel_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Kênh áp dụng'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='shortcut',
            field=models.CharField(max_length=30, unique=True, verbose_name='Phím tắt (/...)'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, verbose_name='Bật tự động phản hồi'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='auto_reply_text',
            field=models.TextField(blank=True, verbose_name='Nội dung tự động phản hồi'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Avatar kênh'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='business_hours_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc làm việc'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='business_hours_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu làm việc'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='channel_type',
            field=models.CharField(choices=[('ZALO', 'Zalo Official Account'), ('MESSENGER', 'Facebook Messenger'), ('WEBCHAT', 'Website Chat Widget'), ('EMAIL', 'Email')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='fb_app_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook App ID'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='fb_app_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='App Secret'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='fb_page_access_token',
            field=models.TextField(blank=True, verbose_name='Page Access Token'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='fb_page_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook Page ID'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='fb_verify_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Webhook Verify Token'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên kênh'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Tắt'), ('ERROR', 'Lỗi kết nối')], default='INACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='webchat_allowed_origins',
            field=models.TextField(blank=True, help_text='VD: https://vietmedi.vn', verbose_name='Allowed Origins (mỗi domain 1 dòng)'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='webchat_greeting',
            field=models.CharField(blank=True, default='Xin chào! Chúng tôi có thể giúp gì cho bạn?', max_length=255),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='webchat_offline_message',
            field=models.CharField(blank=True, default='Hiện tại chúng tôi đang offline. Chúng tôi sẽ phản hồi sớm nhất!', max_length=255),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='webchat_position',
            field=models.CharField(choices=[('bottom-right', 'Dưới phải'), ('bottom-left', 'Dưới trái')], default='bottom-right', max_length=12),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='webchat_theme_color',
            field=models.CharField(default='#1a5276', max_length=7, verbose_name='Màu theme widget'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='zalo_access_token',
            field=models.TextField(blank=True, verbose_name='Zalo Access Token'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='zalo_oa_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zalo OA ID'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='zalo_refresh_token',
            field=models.TextField(blank=True, verbose_name='Zalo Refresh Token'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='zalo_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zalo Secret Key'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='zalo_webhook_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zalo Webhook Token'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_contacts_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Agent phụ trách'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên công ty'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu bổ sung từ file'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hẹn follow-up'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú tổng'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_raw',
            field=models.CharField(db_index=True, max_length=20, verbose_name='SĐT (raw)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='row_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Số hàng trong file'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('NEW', 'Mới'), ('ASSIGNED', 'Đã phân công'), ('CALLING', 'Đang liên hệ'), ('REACHED', 'Đã liên hệ được'), ('NOT_REACHED', 'Không liên hệ được'), ('INTERESTED', 'Quan tâm'), ('NOT_INTERESTED', 'Không quan tâm'), ('FOLLOW_UP', 'Cần theo dõi thêm'), ('CONVERTED', 'Đã chốt'), ('DO_NOT_CALL', 'Không gọi lại')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='allow_full_phone_groups',
            field=models.JSONField(default=list, help_text='VD: ["Manager","Engagement Lead"]', verbose_name='Nhóm được xem SĐT đầy đủ'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_lists_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Team lead phụ trách'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='campaign_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nhãn chiến dịch'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh sách'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagement_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Agent phụ trách'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='csat_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='CSAT (1-5)'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên khách hàng'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='ID người dùng trên platform'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='first_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phản hồi đầu tiên'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='internal_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú nội bộ'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='linked_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='engagement.contact', verbose_name='Liên kết contact'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chủ đề'),
        ),
        migrations.AlterField(
            model_name='conversationtag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('IN', 'Đến (từ khách)'), ('OUT', 'Đi (từ agent)')], db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Ghi chú nội bộ (không gửi KH)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('TEXT', 'Văn bản'), ('IMAGE', 'Hình ảnh'), ('FILE', 'File'), ('STICKER', 'Sticker'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('TEMPLATE', 'Template'), ('EVENT', 'Sự kiện hệ thống')], default='TEXT', max_length=10),
        ),
        migrations.AlterModelTable(
            name='calllog',
            table='engagement_call_log',
        ),
        migrations.AlterModelTable(
            name='cannedresponse',
            table='engagement_canned_response',
        ),
        migrations.AlterModelTable(
            name='conversationtag',
            table='engagement_conversation_tag',
        ),
        migrations.AlterModelTable(
            name='message',
            table='engagement_message',
        ),
    ]
