# Generated by Django 5.2 on 2026-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_alter_calllog_options_alter_cannedresponse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='allow_full_phone_groups',
            field=models.JSONField(default=list, help_text='VD: ["Managers","Engagement Lead"]', verbose_name='Nhóm được xem SĐT đầy đủ'),
        ),
    ]
