# Generated by Django 5.2 on 2026-03-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Nhóm khám',
                'verbose_name_plural': 'Nhóm khám',
                'db_table': 'catalogs_group_checkup',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('group_checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalogs.groupcheckup')),
            ],
            options={
                'verbose_name': 'Danh mục khám',
                'verbose_name_plural': 'Danh mục khám',
                'db_table': 'catalogs_checkup_category',
                'ordering': ['group_checkup__name', 'id'],
            },
        ),
    ]
