# Generated by Django 5.2 on 2026-04-02 04:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkupcategory',
            options={'ordering': ['group_checkup__display_order', 'group_checkup__name', 'display_order', 'id'], 'verbose_name': 'Danh mục khám', 'verbose_name_plural': 'Danh mục khám'},
        ),
        migrations.AlterModelOptions(
            name='groupcheckup',
            options={'ordering': ['display_order', 'name', 'id'], 'verbose_name': 'Nhóm khám', 'verbose_name_plural': 'Nhóm khám'},
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkup_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='for_female_family',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='for_female_single',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='for_male',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='list_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='price_female_family',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='price_female_single',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='price_male',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='price_type',
            field=models.CharField(choices=[('standard', 'Tiêu chuẩn'), ('free', 'Miễn phí'), ('gift', 'Tặng')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='subgroup_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='checkupcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_checkup_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcheckup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='groupcheckup',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupcheckup',
            name='group_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groupcheckup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupcheckup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='CheckupPackageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_package_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_checkup_package_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gói khám mẫu',
                'verbose_name_plural': 'Gói khám mẫu',
                'db_table': 'catalogs_checkup_package_template',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckupPackageTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='catalogs.checkupcategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogs.checkuppackagetemplate')),
            ],
            options={
                'verbose_name': 'Dòng gói khám mẫu',
                'verbose_name_plural': 'Dòng gói khám mẫu',
                'db_table': 'catalogs_checkup_package_template_item',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='checkuppackagetemplate',
            name='categories',
            field=models.ManyToManyField(related_name='package_templates', through='catalogs.CheckupPackageTemplateItem', to='catalogs.checkupcategory'),
        ),
        migrations.AddConstraint(
            model_name='checkuppackagetemplateitem',
            constraint=models.UniqueConstraint(fields=('package', 'category'), name='uq_catalogs_package_category'),
        ),
        migrations.AddConstraint(
            model_name='checkuppackagetemplate',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='uq_catalogs_package_name_per_user'),
        ),
    ]
