# Generated by Django 5.2 on 2026-03-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('default_am_slot_limit', models.PositiveIntegerField(default=100, verbose_name='Giới hạn slot mặc định buổi sáng')),
                ('default_pm_slot_limit', models.PositiveIntegerField(default=100, verbose_name='Giới hạn slot mặc định buổi chiều')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_general_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thiết lập chung hệ thống',
                'verbose_name_plural': 'Thiết lập chung hệ thống',
                'db_table': 'core_system_general_setting',
            },
        ),
    ]
