# Generated by Django 5.2 on 2026-04-10 03:37

import apps.clinical.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('file_url', models.FileField(upload_to=apps.clinical.models.pathology_upload_path)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('auto_extracted_conclusion', models.TextField(blank=True, null=True)),
                ('manual_conclusion', models.TextField(blank=True, null=True)),
                ('evaluation', models.CharField(blank=True, choices=[('normal', 'Bình thường'), ('follow', 'Theo dõi')], max_length=10, null=True, verbose_name='Đánh giá')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pathology Result',
                'verbose_name_plural': 'Pathology Results',
                'db_table': 'clinic_pathologyresult',
                'ordering': ['-result_date', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToothNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('description_vi', models.CharField(max_length=200)),
                ('description_en', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tooth Notation',
                'verbose_name_plural': 'Tooth Notations',
                'db_table': 'clinical_toothnotation',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DentalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(blank=True)),
                ('tooth_data', models.JSONField(default=dict)),
                ('tooth_loss_classification', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3)),
                ('other_oral_conditions', models.TextField(blank=True)),
                ('chewing_ability', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('health_classification', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=3)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_dental_examinations', to='organizations.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_dental_examinations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dental Examination',
                'verbose_name_plural': 'Dental Examinations',
                'db_table': 'clinical_dentalexamination',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
