# Generated by Django 5.2 on 2026-04-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_dentalexamination_patient_snapshot'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalexamination',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Dental Examination', 'verbose_name_plural': 'Dental Examinations'},
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_dental_examinations', to='organizations.company'),
        ),
    ]
