# Generated by Django 5.2 on 2026-04-22 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_dentalexamination_options_and_more'),
        ('his_integration', '0001_initial'),
        ('patients', '0002_hispatientsync_hissyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalexamination',
            name='his_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_examinations', to='his_integration.hispatientsync', verbose_name='Bệnh nhân HIS'),
        ),
        migrations.AlterField(
            model_name='dentalexamination',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_dental_examinations', to='patients.patient'),
        ),
    ]
