# Generated by Django 5.2 on 2026-04-15 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_completion', '0002_recordcompletionlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordcompletionlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_completion_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AlterField(
            model_name='recordcompletionlog',
            name='confirmed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='recordcompletionlog',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú / Lý do'),
        ),
    ]
