# Generated by Django 5.2 on 2026-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_submission_fields_and_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
