# Generated by Django 5.2 on 2026-03-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateContractProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('company_name_snapshot', models.CharField(max_length=255)),
                ('company_address_snapshot', models.TextField(blank=True, null=True)),
                ('company_tax_code_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('company_phone_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_title_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_single_count', models.PositiveIntegerField(default=0)),
                ('female_family_count', models.PositiveIntegerField(default=0)),
                ('signer_a_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_a_title', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_b_name', models.CharField(blank=True, max_length=255, null=True)),
                ('signer_b_title', models.CharField(blank=True, max_length=255, null=True)),
                ('quotation_note', models.TextField(blank=True, null=True)),
                ('contract_note', models.TextField(blank=True, null=True)),
                ('subtotal_male', models.BigIntegerField(default=0)),
                ('subtotal_female_single', models.BigIntegerField(default=0)),
                ('subtotal_female_family', models.BigIntegerField(default=0)),
                ('grand_total', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to='booking.healthcontract')),
            ],
            options={
                'verbose_name': 'Corporate Contract Profile',
                'verbose_name_plural': 'Corporate Contract Profiles',
                'db_table': 'contracts_corporate_profile',
                'ordering': ['-id'],
            },
        ),
    ]
