# Generated by Django 5.2 on 2026-03-29 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_is_locked_contract_locked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issueddocument',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='contract.contract'),
        ),
        migrations.AddIndex(
            model_name='issueddocument',
            index=models.Index(fields=['contract', 'doc_type'], name='contract_is_contrac_26f786_idx'),
        ),
    ]
