# Generated by Django 5.2 on 2026-03-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_issueddocument_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractserviceline',
            name='price_type',
            field=models.CharField(choices=[('standard', 'Tiêu chuẩn'), ('free', 'Miễn phí'), ('gift', 'Tặng')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='contractserviceline',
            name='source_quotation_line_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contractserviceline',
            name='subgroup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractserviceline',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contractserviceline',
            name='price_female_family',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contractserviceline',
            name='price_female_single',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='contractserviceline',
            name='price_male',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
