# Generated by Django 5.2 on 2026-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractserviceline_price_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bộ đếm số hợp đồng',
                'verbose_name_plural': 'Bộ đếm số hợp đồng',
                'db_table': 'contract_number_sequence',
                'ordering': ['-year'],
            },
        ),
    ]
