# Generated by Django 5.2 on 2026-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_contractnumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecontractprofile',
            name='blood_collection_from_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ bắt đầu lấy mẫu'),
        ),
        migrations.AddField(
            model_name='corporatecontractprofile',
            name='blood_collection_to_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ kết thúc lấy mẫu'),
        ),
        migrations.AddField(
            model_name='corporatecontractprofile',
            name='deposit_amount_words',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Số tiền đặt cọc bằng chữ'),
        ),
    ]
