# Generated by Django 5.2 on 2026-03-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_corporatecontractprofile_blood_collection_from_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_plan', to='contract.contract')),
            ],
            options={
                'verbose_name': 'Kế hoạch triển khai',
                'verbose_name_plural': 'Kế hoạch triển khai',
                'db_table': 'contract_implementation_plan',
                'ordering': ['-id'],
            },
        ),
    ]
