# Generated by Django 5.2 on 2026-03-31 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_implementationplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractserviceline',
            name='discount_ff_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contractserviceline',
            name='discount_fs_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contractserviceline',
            name='discount_male_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
