# Generated by Django 5.2 on 2026-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_quotationline_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatecontractprofile',
            name='package_snapshot_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Snapshot gói khám từ báo giá'),
        ),
        migrations.AddField(
            model_name='corporatecontractprofile',
            name='quotation_extra_content_snapshot',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung bổ sung snapshot từ báo giá'),
        ),
    ]
