# Generated by Django 5.2 on 2026-04-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='helpdesk_ti_status_6d13e0_idx',
            old_name='helpdesk_ti_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='helpdesk_ti_created_4c3a83_idx',
            old_name='helpdesk_ti_creator_idx',
        ),
    ]
