# Generated by Django 5.2 on 2026-03-26 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255, verbose_name='Người báo cáo (tự động lấy từ tài khoản, có thể chỉnh lại)')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Khoa/phòng báo cáo')),
                ('patient_name', models.CharField(blank=True, max_length=255, verbose_name='Họ tên bệnh nhân (nếu có)')),
                ('patient_code', models.CharField(blank=True, max_length=50, verbose_name='Mã bệnh nhân / mã hồ sơ (nếu có)')),
                ('incident_type', models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra'), ('OCCURRED', 'Đã xảy ra')], default='OCCURRED', max_length=100, verbose_name='Phân loại sự cố')),
                ('incident_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xảy ra')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vị trí / khu vực xảy ra')),
                ('related_policy', models.TextField(blank=True, help_text='Nếu chưa có quy trình, ghi rõ: "Chưa có quy trình/chính sách điều chỉnh".', verbose_name='Quy trình / chính sách liên quan (nếu có)')),
                ('incident_name', models.CharField(blank=True, choices=[('wrong_diagnosis', 'Chẩn đoán sai / chậm chẩn đoán'), ('wrong_treatment', 'Chỉ định điều trị / thủ thuật không phù hợp'), ('test_error', 'Sai sót xét nghiệm (lấy mẫu, nhãn, xử lý, trả kết quả)'), ('procedure_error', 'Sai sót kỹ thuật / thủ thuật'), ('clinical_other', 'Khác (chuyên môn) – ghi rõ ở phần mô tả'), ('billing_error', 'Sai sót thu ngân / thanh toán'), ('insurance_error', 'Sai sót BHYT (hưởng sai, nhập sai thông tin, từ chối không đúng)'), ('data_entry_error', 'Nhập liệu hành chính sai / thiếu (họ tên, ngày sinh, địa chỉ...)'), ('admin_other', 'Khác (hành chính) – ghi rõ ở phần mô tả'), ('rude_behavior', 'Thái độ/giao tiếp chưa phù hợp'), ('info_miscomm', 'Truyền đạt thông tin sai / không đầy đủ cho khách hàng'), ('cskh_other', 'Khác (CSKH) – ghi rõ ở phần mô tả'), ('aseptic_break', 'Không tuân thủ vô khuẩn / vệ sinh tay'), ('waste_error', 'Phân loại / xử lý rác y tế không đúng'), ('ic_other', 'Khác (KSNK) – ghi rõ ở phần mô tả'), ('fall', 'Ngã / suýt ngã trong cơ sở'), ('drug_allergy', 'Dị ứng thuốc (đã biết / chưa được khai thác) '), ('med_error', 'Sai sót dùng thuốc (nhầm liều, nhầm thuốc, nhầm người bệnh...)'), ('safety_other', 'Khác (an toàn NB) – ghi rõ ở phần mô tả'), ('device_failure', 'Thiết bị hỏng / lỗi trong khi sử dụng'), ('device_unavail', 'Thiết bị không sẵn sàng khi cần'), ('equip_other', 'Khác (trang thiết bị) – ghi rõ ở phần mô tả'), ('system_down', 'Phần mềm / hệ thống bị treo / không truy cập được'), ('data_loss', 'Mất dữ liệu / sai lệch dữ liệu trên hệ thống'), ('integration_error', 'Lỗi kết nối giữa các phần mềm (HIS, LIS, PACS…)'), ('it_other', 'Khác (CNTT) – ghi rõ ở phần mô tả')], max_length=50, verbose_name='Mã tên sự cố')),
                ('description', models.TextField(help_text='Mô tả từ khi bắt đầu, điều kiện, hoàn cảnh, diễn biến, các tác nhân tham gia, ai liên quan...', verbose_name='Mô tả diễn biến / cơ chế sự cố')),
                ('consequence', models.TextField(blank=True, help_text="Nếu chưa xảy ra hậu quả ghi: 'Chưa xảy ra hậu quả' hoặc 'Suýt xảy ra hậu quả' và mô tả hậu quả có thể xảy ra.", verbose_name='Hậu quả thực tế hoặc nguy cơ có thể xảy ra')),
                ('severity', models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra, không gây hậu quả'), ('NO_HARM', 'Đã xảy ra nhưng chưa gây hại'), ('MINOR', 'Nhẹ'), ('MODERATE', 'Trung bình'), ('SEVERE', 'Nặng'), ('DEATH', 'Tử vong')], max_length=100, verbose_name='Mức độ nghiêm trọng')),
                ('immediate_action', models.TextField(blank=True, help_text='Đã báo cáo cho ai, khi nào? Đã làm gì ngay sau khi phát hiện để giảm hậu quả?', verbose_name='Hành động báo cáo & khắc phục tức thời')),
                ('followup_action_quality', models.TextField(blank=True, help_text='Ví dụ: phân tích nguyên nhân gốc rễ, cảnh báo toàn viện, xây dựng quy trình...', verbose_name='Hành động/đề xuất của bộ phận QLCL')),
                ('followup_action_department', models.TextField(blank=True, help_text='Các việc cần làm, người phụ trách, thời gian hoàn thành.', verbose_name='Hành động/đề xuất của khoa/phòng liên quan')),
                ('training_plan', models.TextField(blank=True, verbose_name='Nhu cầu phổ biến / huấn luyện lại quy trình (nếu có)')),
                ('other_corrective_actions', models.TextField(blank=True, verbose_name='Hành động khắc phục khác')),
                ('attachment_note', models.TextField(blank=True, help_text='Ghi đường dẫn file, vị trí lưu, hoặc mô tả tài liệu đính kèm.', verbose_name='Hình ảnh / tài liệu / trích camera đính kèm')),
                ('is_anonymous_to_department', models.BooleanField(default=False, verbose_name='Ẩn tên người báo cáo khi gửi báo cáo cho khoa/phòng')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo sự cố y khoa',
                'verbose_name_plural': 'Báo cáo sự cố y khoa',
                'ordering': ['-incident_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='quality/incidents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quality.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Họ tên khách hàng')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('patient_code', models.CharField(blank=True, max_length=50, verbose_name='Mã bệnh nhân / mã hồ sơ khám')),
                ('clinic_room', models.CharField(blank=True, max_length=100, verbose_name='Phòng khám / chuyên khoa')),
                ('doctor_name', models.CharField(blank=True, max_length=120, verbose_name='Bác sĩ khám')),
                ('q1_name_uppercase', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='1. Họ tên người bệnh viết in hoa, có đánh dấu')),
                ('q2_no_erasure', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='2. Ghi đầy đủ các mục, không sửa chữa/tẩy xóa/rách; sửa chữa đúng quy định (gạch ngang viết lại, không viết đè, có chữ ký nháy của người sửa)')),
                ('q3_documents_sorted', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='3. Các loại giấy tờ, kết quả xét nghiệm được sắp xếp đúng nhóm, theo thứ tự thời gian trước - sau')),
                ('q4_page_numbered', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='4. Có đánh số thứ tự trên HSBA')),
                ('q5_signatures', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='5. Có đầy đủ chữ ký (bác sĩ, điều dưỡng, khách hàng) trên các trang cần ký')),
                ('q6_icd_code', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='6. Ghi mã CD phù hợp với chẩn đoán')),
                ('q7_history_exam_full', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='7. Hỏi tiền sử bệnh, tiền sử chi tiết; khám NB toàn diện, ghi bệnh án đầy đủ')),
                ('q8_tests_ordered', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='8. Chỉ định đầy đủ các xét nghiệm lâm sàng')),
                ('q9_results_reviewed', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='9. KQ lâm sàng, CLS được BS xem, xử trí, ký và ghi rõ họ tên')),
                ('q10_diagnosis_change_noted', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='10. Thay đổi chẩn đoán, các thay đổi trên tờ điều trị có ghi rõ lý luận và cập nhật ngày giờ thay đổi')),
                ('q11_discharge_summary', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='11. Khi ra viện có ghi rõ chẩn đoán xác định, chẩn đoán phân biệt; có tóm tắt HSBA điều trị')),
                ('q12_progress_notes', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='12. Ghi diễn tiến điều trị, chăm sóc hằng ngày theo trình tự thời gian (giờ - ngày); ký - ghi rõ họ tên BS/ĐD; NB nặng ghi diễn tiến theo ngày; kẻ ngang khi hết ngày')),
                ('q13_orders_appropriate', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='13. Y lệnh điều trị hằng ngày phù hợp với chẩn đoán và diễn tiến bệnh, bám sát phác đồ điều trị chuẩn; chỉ định thuốc an toàn, hợp lý, hiệu quả')),
                ('q14_complex_case_noted', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='14. Các trường hợp phức tạp có chỉ định HC, thực hiện HCCM, HC dùng thuốc chấm sao được ghi rõ ràng, chi tiết vào HSBA')),
                ('q15_vital_signs_chart', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='15. Phiếu theo dõi chức năng sống ghi đầy đủ, chi tiết các mục: mạch (đỏ), nhiệt độ (xanh), huyết áp, BMI, nhịp thở,...')),
                ('q16_infusion_record', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='16. Phiếu truyền dịch ghi đầy đủ giờ bắt đầu - kết thúc, tốc độ truyền, liều lượng, số lô, BS chỉ định, ĐD thực hiện; kẻ ngang khi hết ngày')),
                ('q17_blood_transfusion_record', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='17. Phiếu truyền máu ghi đầy đủ các mục theo quy định an toàn truyền máu')),
                ('q18_skin_test_record', models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='18. Phiếu thử phản ứng ghi đầy đủ thông tin, bằng chữ (âm tính, dương tính); ký và ghi rõ họ tên ĐD thực hiện, BS đọc kết quả')),
                ('overall_comment', models.TextField(blank=True, null=True, verbose_name='Nhận xét chung / điểm cần cải tiến')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outpatient_record_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiểm tra hồ sơ khám ngoại trú',
                'verbose_name_plural': 'Kiểm tra hồ sơ khám ngoại trú',
                'ordering': ['-created_at'],
            },
        ),
    ]
