# Generated by Django 5.2 on 2025-12-04 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xảy ra')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Vị trí/khoa phòng')),
                ('patient_name', models.CharField(blank=True, max_length=255, verbose_name='Họ tên bệnh nhân (nếu có)')),
                ('patient_code', models.CharField(blank=True, max_length=50, verbose_name='Mã BN/HSBA')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề ngắn')),
                ('description', models.TextField(verbose_name='Mô tả sự cố')),
                ('immediate_action', models.TextField(blank=True, verbose_name='Xử trí ngay sau sự cố')),
                ('severity', models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra (near miss)'), ('MINOR', 'Nhẹ'), ('MODERATE', 'Trung bình'), ('SEVERE', 'Nặng'), ('DEATH', 'Tử vong')], max_length=20, verbose_name='Mức độ nghiêm trọng')),
                ('is_anonymous_to_department', models.BooleanField(default=False, verbose_name='Ẩn tên với khoa/phòng khi tổng hợp báo cáo')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo sự cố y khoa',
                'verbose_name_plural': 'Báo cáo sự cố y khoa',
                'ordering': ['-incident_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Họ tên khách hàng')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('patient_code', models.CharField(blank=True, max_length=50, verbose_name='Mã bệnh nhân / mã hồ sơ khám')),
                ('clinic_room', models.CharField(blank=True, max_length=100, verbose_name='Phòng khám / chuyên khoa')),
                ('doctor_name', models.CharField(blank=True, max_length=120, verbose_name='Bác sĩ khám')),
                ('q1_admin_info_full', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='1. Thông tin hành chính (họ tên, ngày sinh/tuổi, giới, địa chỉ, SĐT) được ghi đầy đủ')),
                ('q2_patient_id_clear', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='2. Có mã bệnh nhân / mã hồ sơ khám rõ ràng, thống nhất giữa các phiếu')),
                ('q3_insurance_info', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='3. Thông tin BHYT (nếu có) được ghi đầy đủ, đúng quy định')),
                ('q4_no_erasures', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='4. Hồ sơ không tẩy xoá; nếu sửa chữa có gạch bỏ, ký xác nhận, ghi ngày giờ')),
                ('q5_signatures', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='5. Đầy đủ chữ ký của bác sĩ, điều dưỡng (nếu có), và khách hàng tại các mục cần ký')),
                ('q6_documents_order', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='6. Giấy tờ, phiếu xét nghiệm, đơn thuốc được sắp xếp khoa học theo trình tự thời gian khám')),
                ('q7_reason_for_visit', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='7. Lý do khám, thời gian diễn tiến bệnh được ghi rõ ràng')),
                ('q8_history_full', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='8. Bệnh sử, tiền sử liên quan (bản thân, gia đình, dị ứng, dùng thuốc, thai sản...) được khai thác đầy đủ')),
                ('q9_vital_signs', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='9. Ghi đầy đủ sinh hiệu phù hợp (mạch, HA, nhiệt độ, nhịp thở, SpO₂, cân nặng, chiều cao, BMI... tuỳ trường hợp)')),
                ('q10_physical_exam', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='10. Khám thực thể đầy đủ, phù hợp với lý do khám (khám toàn thân + cơ quan liên quan)')),
                ('q11_risk_screening', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='11. Có sàng lọc các yếu tố nguy cơ (THA, ĐTĐ, tim mạch, thai nghén, bệnh truyền nhiễm...) khi phù hợp')),
                ('q12_diagnosis_consistent', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='12. Chẩn đoán phù hợp với triệu chứng, khám lâm sàng và cận lâm sàng (nếu có)')),
                ('q13_tests_indicated', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='13. Chỉ định cận lâm sàng phù hợp với hướng chẩn đoán, không thừa / thiếu rõ rệt')),
                ('q14_results_available', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='14. Kết quả cận lâm sàng được lưu trong hồ sơ (bản giấy hoặc điện tử) và dễ truy xuất')),
                ('q15_results_reviewed', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='15. Có ghi nhận bác sĩ đã xem, đánh giá kết quả và điều chỉnh chẩn đoán / điều trị (nếu cần)')),
                ('q16_treatment_plan', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='16. Kế hoạch điều trị / xử trí được ghi rõ (điều trị tại chỗ, cho về, chuyển tuyến, tư vấn...)')),
                ('q17_prescription_safe', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='17. Đơn thuốc ghi đầy đủ: tên thuốc, hàm lượng, liều dùng, số lần trong ngày, đường dùng, thời gian điều trị')),
                ('q18_drug_allergy_checked', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='18. Có hỏi và ghi nhận tiền sử dị ứng thuốc trước khi kê đơn')),
                ('q19_interactions_checked', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='19. Đơn thuốc không có tương tác, chống chỉ định rõ rệt hoặc đã ghi chú, cân nhắc nguy cơ–lợi ích')),
                ('q20_education_documented', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='20. Có ghi nhận việc tư vấn cho người bệnh: cách dùng thuốc, chế độ ăn uống – sinh hoạt, dấu hiệu cần đi khám lại ngay')),
                ('q21_followup_plan', models.CharField(choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=10, verbose_name='21. Có hẹn tái khám rõ ràng (thời điểm, lý do) hoặc ghi điều kiện tái khám')),
                ('overall_comment', models.TextField(blank=True, verbose_name='Nhận xét chung / điểm cần cải tiến')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outpatient_record_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiểm tra hồ sơ khám ngoại trú',
                'verbose_name_plural': 'Kiểm tra hồ sơ khám ngoại trú',
                'ordering': ['-created_at'],
            },
        ),
    ]
