# Generated by Django 5.2 on 2025-12-05 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='title',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='attachment_note',
            field=models.TextField(blank=True, help_text='Ghi đường dẫn file, vị trí lưu, hoặc mô tả tài liệu đính kèm.', verbose_name='Hình ảnh / tài liệu / trích camera đính kèm'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='consequence',
            field=models.TextField(blank=True, help_text="Nếu chưa xảy ra hậu quả ghi: 'Chưa xảy ra hậu quả' hoặc 'Suýt xảy ra hậu quả' và mô tả hậu quả có thể xảy ra.", verbose_name='Hậu quả thực tế hoặc nguy cơ có thể xảy ra'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Khoa/phòng báo cáo'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='followup_action_department',
            field=models.TextField(blank=True, help_text='Các việc cần làm, người phụ trách, thời gian hoàn thành.', verbose_name='Hành động/đề xuất của khoa/phòng liên quan'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='followup_action_quality',
            field=models.TextField(blank=True, help_text='Ví dụ: phân tích nguyên nhân gốc rễ, cảnh báo toàn viện, xây dựng quy trình...', verbose_name='Hành động/đề xuất của bộ phận QLCL'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ví dụ: Nhầm thuốc, trượt ngã tại khu vực chờ, lỗi nhập nhầm kết quả...', max_length=255, verbose_name='Tên sự cố (mô tả ngắn gọn)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra'), ('OCCURRED', 'Đã xảy ra')], default='OCCURRED', max_length=20, verbose_name='Phân loại sự cố'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='other_corrective_actions',
            field=models.TextField(blank=True, verbose_name='Hành động khắc phục khác'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='related_policy',
            field=models.TextField(blank=True, help_text='Nếu chưa có quy trình, ghi rõ: "Chưa có quy trình/chính sách điều chỉnh".', verbose_name='Quy trình / chính sách liên quan (nếu có)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Người báo cáo (tự động lấy từ tài khoản, có thể chỉnh lại)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='training_plan',
            field=models.TextField(blank=True, verbose_name='Nhu cầu phổ biến / huấn luyện lại quy trình (nếu có)'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='description',
            field=models.TextField(help_text='Mô tả từ khi bắt đầu, điều kiện, hoàn cảnh, diễn biến, các tác nhân tham gia, ai liên quan...', verbose_name='Mô tả diễn biến / cơ chế sự cố'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='immediate_action',
            field=models.TextField(blank=True, help_text='Đã báo cáo cho ai, khi nào? Đã làm gì ngay sau khi phát hiện để giảm hậu quả?', verbose_name='Hành động báo cáo & khắc phục tức thời'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='is_anonymous_to_department',
            field=models.BooleanField(default=False, verbose_name='Ẩn tên người báo cáo khi gửi báo cáo cho khoa/phòng'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vị trí / khu vực xảy ra'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='patient_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã bệnh nhân / mã hồ sơ (nếu có)'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra, không gây hậu quả'), ('NO_HARM', 'Đã xảy ra nhưng chưa gây hại'), ('MINOR', 'Nhẹ'), ('MODERATE', 'Trung bình'), ('SEVERE', 'Nặng'), ('DEATH', 'Tử vong')], max_length=20, verbose_name='Mức độ nghiêm trọng'),
        ),
    ]
