# Generated by Django 5.2 on 2025-12-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_remove_incidentreport_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_name',
            field=models.CharField(blank=True, choices=[('wrong_diagnosis', 'Chẩn đoán sai / chậm chẩn đoán'), ('wrong_treatment', 'Chỉ định điều trị / thủ thuật không phù hợp'), ('test_error', 'Sai sót xét nghiệm (lấy mẫu, nhãn, xử lý, trả kết quả)'), ('procedure_error', 'Sai sót kỹ thuật / thủ thuật'), ('clinical_other', 'Khác (chuyên môn) – ghi rõ ở phần mô tả'), ('billing_error', 'Sai sót thu ngân / thanh toán'), ('insurance_error', 'Sai sót BHYT (hưởng sai, nhập sai thông tin, từ chối không đúng)'), ('data_entry_error', 'Nhập liệu hành chính sai / thiếu (họ tên, ngày sinh, địa chỉ...)'), ('admin_other', 'Khác (hành chính) – ghi rõ ở phần mô tả'), ('rude_behavior', 'Thái độ/giao tiếp chưa phù hợp'), ('info_miscomm', 'Truyền đạt thông tin sai / không đầy đủ cho khách hàng'), ('cskh_other', 'Khác (CSKH) – ghi rõ ở phần mô tả'), ('aseptic_break', 'Không tuân thủ vô khuẩn / vệ sinh tay'), ('waste_error', 'Phân loại / xử lý rác y tế không đúng'), ('ic_other', 'Khác (KSNK) – ghi rõ ở phần mô tả'), ('fall', 'Ngã / suýt ngã trong cơ sở'), ('drug_allergy', 'Dị ứng thuốc (đã biết / chưa được khai thác) '), ('med_error', 'Sai sót dùng thuốc (nhầm liều, nhầm thuốc, nhầm người bệnh...)'), ('safety_other', 'Khác (an toàn NB) – ghi rõ ở phần mô tả'), ('device_failure', 'Thiết bị hỏng / lỗi trong khi sử dụng'), ('device_unavail', 'Thiết bị không sẵn sàng khi cần'), ('equip_other', 'Khác (trang thiết bị) – ghi rõ ở phần mô tả'), ('system_down', 'Phần mềm / hệ thống bị treo / không truy cập được'), ('data_loss', 'Mất dữ liệu / sai lệch dữ liệu trên hệ thống'), ('integration_error', 'Lỗi kết nối giữa các phần mềm (HIS, LIS, PACS…)'), ('it_other', 'Khác (CNTT) – ghi rõ ở phần mô tả')], max_length=50, verbose_name='Mã tên sự cố'),
        ),
    ]
