# Generated by Django 5.2 on 2026-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_incidentattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q10_physical_exam',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q11_risk_screening',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q12_diagnosis_consistent',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q13_tests_indicated',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q14_results_available',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q15_results_reviewed',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q16_treatment_plan',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q17_prescription_safe',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q18_drug_allergy_checked',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q19_interactions_checked',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q1_admin_info_full',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q20_education_documented',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q21_followup_plan',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q2_patient_id_clear',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q3_insurance_info',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q4_no_erasures',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q6_documents_order',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q7_reason_for_visit',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q8_history_full',
        ),
        migrations.RemoveField(
            model_name='medicalrecordaudit',
            name='q9_vital_signs',
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q10_diagnosis_change_noted',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='10. Thay đổi chẩn đoán, các thay đổi trên tờ điều trị có ghi rõ lý luận và cập nhật ngày giờ thay đổi'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q11_discharge_summary',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='11. Khi ra viện có ghi rõ chẩn đoán xác định, chẩn đoán phân biệt; có tóm tắt HSBA điều trị'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q12_progress_notes',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='12. Ghi diễn tiến điều trị, chăm sóc hằng ngày theo trình tự thời gian (giờ - ngày); ký - ghi rõ họ tên BS/ĐD; NB nặng ghi diễn tiến theo ngày; kẻ ngang khi hết ngày'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q13_orders_appropriate',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='13. Y lệnh điều trị hằng ngày phù hợp với chẩn đoán và diễn tiến bệnh, bám sát phác đồ điều trị chuẩn; chỉ định thuốc an toàn, hợp lý, hiệu quả'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q14_complex_case_noted',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='14. Các trường hợp phức tạp có chỉ định HC, thực hiện HCCM, HC dùng thuốc chấm sao được ghi rõ ràng, chi tiết vào HSBA'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q15_vital_signs_chart',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='15. Phiếu theo dõi chức năng sống ghi đầy đủ, chi tiết các mục: mạch (đỏ), nhiệt độ (xanh), huyết áp, BMI, nhịp thở,...'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q16_infusion_record',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='16. Phiếu truyền dịch ghi đầy đủ giờ bắt đầu - kết thúc, tốc độ truyền, liều lượng, số lô, BS chỉ định, ĐD thực hiện; kẻ ngang khi hết ngày'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q17_blood_transfusion_record',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='17. Phiếu truyền máu ghi đầy đủ các mục theo quy định an toàn truyền máu'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q18_skin_test_record',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='18. Phiếu thử phản ứng ghi đầy đủ thông tin, bằng chữ (âm tính, dương tính); ký và ghi rõ họ tên ĐD thực hiện, BS đọc kết quả'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q1_name_uppercase',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='1. Họ tên người bệnh viết in hoa, có đánh dấu'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q2_no_erasure',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='2. Ghi đầy đủ các mục, không sửa chữa/tẩy xóa/rách; sửa chữa đúng quy định (gạch ngang viết lại, không viết đè, có chữ ký nháy của người sửa)'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q3_documents_sorted',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='3. Các loại giấy tờ, kết quả xét nghiệm được sắp xếp đúng nhóm, theo thứ tự thời gian trước - sau'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q4_page_numbered',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='4. Có đánh số thứ tự trên HSBA'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q6_icd_code',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='6. Ghi mã CD phù hợp với chẩn đoán'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q7_history_exam_full',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='7. Hỏi tiền sử bệnh, tiền sử chi tiết; khám NB toàn diện, ghi bệnh án đầy đủ'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q8_tests_ordered',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='8. Chỉ định đầy đủ các xét nghiệm lâm sàng'),
        ),
        migrations.AddField(
            model_name='medicalrecordaudit',
            name='q9_results_reviewed',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='9. KQ lâm sàng, CLS được BS xem, xử trí, ký và ghi rõ họ tên'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra'), ('OCCURRED', 'Đã xảy ra')], default='OCCURRED', max_length=100, verbose_name='Phân loại sự cố'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='severity',
            field=models.CharField(choices=[('NEAR_MISS', 'Suýt xảy ra, không gây hậu quả'), ('NO_HARM', 'Đã xảy ra nhưng chưa gây hại'), ('MINOR', 'Nhẹ'), ('MODERATE', 'Trung bình'), ('SEVERE', 'Nặng'), ('DEATH', 'Tử vong')], max_length=100, verbose_name='Mức độ nghiêm trọng'),
        ),
        migrations.AlterField(
            model_name='medicalrecordaudit',
            name='overall_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét chung / điểm cần cải tiến'),
        ),
        migrations.AlterField(
            model_name='medicalrecordaudit',
            name='q5_signatures',
            field=models.CharField(blank=True, choices=[('PASS', 'Đạt'), ('FAIL', 'Không đạt'), ('NA', 'Không áp dụng')], max_length=100, null=True, verbose_name='5. Có đầy đủ chữ ký (bác sĩ, điều dưỡng, khách hàng) trên các trang cần ký'),
        ),
    ]
