# Generated by Django 5.2 on 2026-03-26 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày khám')),
                ('shift', models.CharField(choices=[('AM', 'Sáng'), ('PM', 'Chiều')], max_length=2, verbose_name='Buổi')),
                ('slot_type', models.CharField(choices=[('INDIVIDUAL', 'Khách lẻ'), ('CONTRACT', 'Khách đoàn / hợp đồng')], db_index=True, default='INDIVIDUAL', max_length=20, verbose_name='Loại slot')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Sức chứa')),
                ('booked_count', models.PositiveIntegerField(default=0, verbose_name='Đã đăng ký')),
                ('status', models.CharField(choices=[('OPEN', 'Mở'), ('CLOSED', 'Đóng'), ('CANCELLED', 'Hủy')], db_index=True, default='OPEN', max_length=12, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='contract.contract', verbose_name='Hợp đồng')),
            ],
            options={
                'verbose_name': 'Slot lịch khám',
                'verbose_name_plural': 'Slot lịch khám',
                'db_table': 'scheduling_schedule_slot',
                'ordering': ['date', 'shift', 'id'],
                'indexes': [models.Index(fields=['date', 'shift'], name='scheduling__date_4f0f4e_idx'), models.Index(fields=['slot_type', 'status'], name='scheduling__slot_ty_190e13_idx'), models.Index(fields=['contract', 'date'], name='scheduling__contrac_a3cf20_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='ck_schedule_slot_capacity_gte_0'), models.CheckConstraint(condition=models.Q(('booked_count__gte', 0)), name='ck_schedule_slot_booked_count_gte_0'), models.CheckConstraint(condition=models.Q(('booked_count__lte', models.F('capacity'))), name='ck_schedule_slot_booked_not_exceed_capacity'), models.UniqueConstraint(fields=('date', 'shift', 'slot_type', 'contract'), name='uq_schedule_slot_date_shift_type_contract')],
            },
        ),
    ]
