# Generated by Django 5.2 on 2026-03-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_implementationplan'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_start_date', models.DateField(verbose_name='Ngày bắt đầu khám')),
                ('exam_end_date', models.DateField(verbose_name='Ngày kết thúc khám')),
                ('planned_employee_count', models.PositiveIntegerField(verbose_name='Số khách hàng đăng ký')),
                ('am_capacity_limit', models.PositiveIntegerField(verbose_name='Giới hạn slot sáng áp dụng cho hợp đồng')),
                ('pm_capacity_limit', models.PositiveIntegerField(verbose_name='Giới hạn slot chiều áp dụng cho hợp đồng')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Đăng ký lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='contract.contract', verbose_name='Hợp đồng')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_contract_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng ký lịch khám')),
            ],
            options={
                'verbose_name': 'Cấu hình lịch khám hợp đồng',
                'verbose_name_plural': 'Cấu hình lịch khám hợp đồng',
                'db_table': 'scheduling_contract_schedule_config',
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('planned_employee_count__gt', 0)), name='ck_contract_schedule_config_planned_employee_gt_0'), models.CheckConstraint(condition=models.Q(('am_capacity_limit__gt', 0)), name='ck_contract_schedule_config_am_limit_gt_0'), models.CheckConstraint(condition=models.Q(('pm_capacity_limit__gt', 0)), name='ck_contract_schedule_config_pm_limit_gt_0'), models.CheckConstraint(condition=models.Q(('exam_end_date__gte', models.F('exam_start_date'))), name='ck_contract_schedule_config_end_gte_start')],
            },
        ),
    ]
