# Generated by Django 5.2 on 2026-03-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_implementationplan'),
        ('scheduling', '0002_contractscheduleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractscheduleconfig',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='contract.quotationdraft', verbose_name='Báo giá'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='contract.quotationdraft', verbose_name='Báo giá'),
        ),
    ]
