# Generated by Django 5.2 on 2026-03-30 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_implementationplan'),
        ('scheduling', '0003_contractscheduleconfig_quotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractscheduleconfig',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['date', 'shift', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='contractscheduleconfig',
            name='ck_contract_schedule_config_planned_employee_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='contractscheduleconfig',
            name='ck_contract_schedule_config_am_limit_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='contractscheduleconfig',
            name='ck_contract_schedule_config_pm_limit_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='contractscheduleconfig',
            name='ck_contract_schedule_config_end_gte_start',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='ck_schedule_slot_capacity_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='ck_schedule_slot_booked_count_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='ck_schedule_slot_booked_not_exceed_capacity',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='uq_schedule_slot_date_shift_type_contract',
        ),
        migrations.RemoveIndex(
            model_name='scheduleslot',
            name='scheduling__slot_ty_190e13_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleslot',
            name='scheduling__contrac_a3cf20_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='schedule_sl_date_shift_idx',
            old_name='scheduling__date_4f0f4e_idx',
        ),
        migrations.RemoveField(
            model_name='contractscheduleconfig',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='note',
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='status',
        ),
        migrations.AddField(
            model_name='contractscheduleconfig',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='am_capacity_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Giới hạn slot sáng'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_config', to='contract.corporatecontractprofile', verbose_name='Hợp đồng'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='planned_employee_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số khách hàng đăng ký'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='pm_capacity_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Giới hạn slot chiều'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='contract.quotationdraft', verbose_name='Báo giá'),
        ),
        migrations.AlterField(
            model_name='contractscheduleconfig',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_contract_schedule_configs', to=settings.AUTH_USER_MODEL, verbose_name='Người đăng ký'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='booked_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Đã đặt'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='contract.corporatecontractprofile', verbose_name='Hợp đồng'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='date',
            field=models.DateField(verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='shift',
            field=models.CharField(choices=[('morning', 'Buổi sáng'), ('afternoon', 'Buổi chiều')], max_length=20, verbose_name='Ca'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='slot_type',
            field=models.CharField(choices=[('walkin', 'Khách lẻ'), ('contract', 'Khách đoàn')], max_length=20, verbose_name='Loại slot'),
        ),
        migrations.AddIndex(
            model_name='contractscheduleconfig',
            index=models.Index(fields=['quotation'], name='contract_sc_quotation_idx'),
        ),
        migrations.AddIndex(
            model_name='contractscheduleconfig',
            index=models.Index(fields=['contract'], name='contract_sc_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='contractscheduleconfig',
            index=models.Index(fields=['exam_start_date', 'exam_end_date'], name='contract_sc_exam_range_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['slot_type', 'date'], name='schedule_sl_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['contract', 'date', 'shift'], name='sched_sl_ct_dt_sf_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['quotation', 'date', 'shift'], name='sched_sl_qt_dt_sf_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractscheduleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('planned_employee_count__gte', 0)), name='contract_schedule_cfg_employee_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='contractscheduleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('am_capacity_limit__gte', 0)), name='contract_schedule_cfg_am_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='contractscheduleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('pm_capacity_limit__gte', 0)), name='contract_schedule_cfg_pm_limit_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='contractscheduleconfig',
            constraint=models.CheckConstraint(condition=models.Q(('exam_end_date__gte', models.F('exam_start_date'))), name='contract_schedule_cfg_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='schedule_slot_capacity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__gte', 0)), name='schedule_slot_booked_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', models.F('booked_count'))), name='schedule_slot_capacity_gte_booked_count'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract__isnull', False), ('slot_type', 'contract')), ('contract__isnull', True), _connector='OR'), name='schedule_slot_contract_requires_contract_type'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('contract__isnull', False), ('quotation__isnull', False), ('slot_type', 'walkin'), _connector='OR'), name='schedule_slot_owner_required_for_contract_slots'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('contract__isnull', True), ('quotation__isnull', True), ('slot_type', 'contract'), _negated=True), name='schedule_slot_contract_type_must_have_owner'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('date', 'shift', 'slot_type', 'contract'), name='uq_schedule_slot_date_shift_type_contract_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', True), ('quotation__isnull', False)), fields=('date', 'shift', 'slot_type', 'quotation'), name='uq_schedule_slot_date_shift_type_quotation_when_no_contract'),
        ),
        migrations.AlterModelTable(
            name='contractscheduleconfig',
            table='contract_schedule_config',
        ),
        migrations.AlterModelTable(
            name='scheduleslot',
            table='schedule_slot',
        ),
    ]
