# Generated by Django 5.2 on 2026-03-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_contractscheduleconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBloodCollectionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='Ngày lấy máu')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Địa điểm')),
                ('people_count', models.PositiveIntegerField(default=0, verbose_name='Số khách hàng')),
                ('staff_count', models.PositiveIntegerField(default=0, verbose_name='Số điều dưỡng')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_collection_rows', to='scheduling.contractscheduleconfig', verbose_name='Lịch đăng ký khám')),
            ],
            options={
                'db_table': 'schedule_blood_collection_row',
                'ordering': ['collection_date', 'id'],
                'indexes': [models.Index(fields=['schedule_config', 'collection_date'], name='sched_blood_cfg_date_idx'), models.Index(fields=['collection_date'], name='sched_blood_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('people_count__gte', 0)), name='sched_blood_people_gte_0'), models.CheckConstraint(condition=models.Q(('staff_count__gte', 0)), name='sched_blood_staff_gte_0')],
            },
        ),
    ]
