# Generated by Django 5.2 on 2026-04-08 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_corporatecontractprofile_package_snapshot_json_and_more'),
        ('scheduling', '0005_schedulebloodcollectionrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractscheduleconfig',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Cấu hình lịch khám hợp đồng', 'verbose_name_plural': 'Cấu hình lịch khám hợp đồng'},
        ),
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['date', 'shift', 'id'], 'verbose_name': 'Slot lịch khám', 'verbose_name_plural': 'Slot lịch khám'},
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_capacity_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_booked_count_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_capacity_gte_booked_count',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_contract_requires_contract_type',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_owner_required_for_contract_slots',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='schedule_slot_contract_type_must_have_owner',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='uq_schedule_slot_date_shift_type_contract_nonnull',
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='uq_schedule_slot_date_shift_type_quotation_when_no_contract',
        ),
        migrations.RemoveIndex(
            model_name='scheduleslot',
            name='schedule_sl_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleslot',
            name='sched_sl_ct_dt_sf_idx',
        ),
        migrations.RemoveIndex(
            model_name='scheduleslot',
            name='sched_sl_qt_dt_sf_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleslot',
            new_name='scheduling__date_4f0f4e_idx',
            old_name='schedule_sl_date_shift_idx',
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='quotation',
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Mở'), ('CLOSED', 'Đóng'), ('CANCELLED', 'Hủy')], db_index=True, default='OPEN', max_length=12, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='booked_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Đã đăng ký'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='contract.contract', verbose_name='Hợp đồng'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Tạo lúc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='date',
            field=models.DateField(verbose_name='Ngày khám'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='shift',
            field=models.CharField(choices=[('AM', 'Sáng'), ('PM', 'Chiều')], max_length=20, verbose_name='Buổi'),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='slot_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Khách lẻ'), ('CONTRACT', 'Khách đoàn / hợp đồng')], db_index=True, default='INDIVIDUAL', max_length=20, verbose_name='Loại slot'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['slot_type', 'status'], name='scheduling__slot_ty_190e13_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['contract', 'date'], name='scheduling__contrac_a3cf20_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='ck_schedule_slot_capacity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__gte', 0)), name='ck_schedule_slot_booked_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__lte', models.F('capacity'))), name='ck_schedule_slot_booked_not_exceed_capacity'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('date', 'shift', 'slot_type', 'contract'), name='uq_schedule_slot_date_shift_type_contract'),
        ),
        migrations.AlterModelTable(
            name='scheduleslot',
            table='scheduling_schedule_slot',
        ),
    ]
