# Generated by Django 5.2 on 2026-04-11 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_corporatecontractprofile_package_snapshot_json_and_more'),
        ('scheduling', '0006_alter_contractscheduleconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='uq_schedule_slot_date_shift_type_contract',
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='contract.quotationdraft', verbose_name='Báo giá'),
        ),
        migrations.AddIndex(
            model_name='scheduleslot',
            index=models.Index(fields=['quotation', 'date'], name='scheduling__quotati_531dc8_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('slot_type', 'CONTRACT'), models.Q(('contract__isnull', False), ('quotation__isnull', False), _connector='OR')), models.Q(('slot_type', 'INDIVIDUAL'), ('contract__isnull', True), ('quotation__isnull', True)), _connector='OR'), name='ck_schedule_slot_owner_valid'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('date', 'shift', 'slot_type', 'contract'), name='uq_schedule_slot_date_shift_type_contract'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', True), ('quotation__isnull', False)), fields=('date', 'shift', 'slot_type', 'quotation'), name='uq_schedule_slot_date_shift_type_quotation'),
        ),
    ]
