# Generated by Django 5.2 on 2026-04-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his_integration', '0001_initial'),
        ('scheduling', '0007_remove_scheduleslot_uq_schedule_slot_date_shift_type_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractscheduleconfig',
            name='his_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_configs', to='his_integration.hiscorporatepackagesync', verbose_name='Gói khám HIS'),
        ),
    ]
