# Generated by Django 5.2 on 2026-03-24 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('AM', 'Sáng'), ('PM', 'Chiều')], max_length=2)),
                ('registered_am', models.PositiveIntegerField(default=0)),
                ('registered_pm', models.PositiveIntegerField(default=0)),
                ('limit_am', models.PositiveIntegerField(default=0)),
                ('limit_pm', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.appointmentschedule')),
            ],
            options={
                'unique_together': {('patient', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='CheckupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Checkup/Test Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Price')),
                ('group_checkup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='booking.groupcheckup')),
            ],
        ),
        migrations.CreateModel(
            name='HealthContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('representative_title', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reception_from_date', models.DateField(blank=True, null=True)),
                ('contract_value_text', models.TextField(blank=True, null=True)),
                ('deposit_payment_text', models.TextField(blank=True, null=True)),
                ('settlement_time_text', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terminated', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('terminated_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('for_male', models.BooleanField(default=False)),
                ('for_female_single', models.BooleanField(default=False)),
                ('for_female_family', models.BooleanField(default=False)),
                ('price_male', models.CharField(blank=True, max_length=50, null=True)),
                ('price_female_single', models.CharField(blank=True, max_length=50, null=True)),
                ('price_female_family', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkup_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.checkupcategory')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='booking.healthcontract')),
            ],
            options={
                'verbose_name': 'Chi tiết dịch vụ hợp đồng',
                'verbose_name_plural': 'Chi tiết dịch vụ hợp đồng',
            },
        ),
        migrations.CreateModel(
            name='BloodCollectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='Ngày lấy máu')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm lấy máu')),
                ('people_count', models.PositiveIntegerField(verbose_name='Số người được lấy máu')),
                ('staff_count', models.PositiveIntegerField(verbose_name='Số lượng nhân viên')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_collections', to='booking.healthcontract')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentschedule',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.healthcontract'),
        ),
        migrations.CreateModel(
            name='QuotationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDraftDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('price_male', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('price_female_single', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('price_female_family', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('checked_male', models.BooleanField(blank=True, default=False, null=True)),
                ('checked_female_single', models.BooleanField(blank=True, default=False, null=True)),
                ('checked_female_family', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_type_male', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_value_male', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type_female_single', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_value_female_single', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type_female_family', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_value_female_family', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_details', to='booking.quotationdraft')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='appointmentschedule',
            unique_together={('contract', 'date', 'shift')},
        ),
        migrations.CreateModel(
            name='IndividualBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=32, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã đến quầy'), ('CONVERTED', 'Đã tạo bệnh nhân/appointment'), ('CANCELLED', 'Hủy'), ('NO_SHOW', 'Vắng')], db_index=True, default='PENDING', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_booking', to='booking.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_bookings', to='patients.patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_bookings', to='booking.appointmentschedule')),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'status'], name='booking_ind_phone_3163ca_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'CHECKED_IN'])), fields=('schedule', 'phone'), name='uq_active_booking_by_phone_in_schedule')],
            },
        ),
    ]
