# Generated by Django 5.2 on 2026-03-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã check-in'), ('IN_PROGRESS', 'Đang khám'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy'), ('NO_SHOW', 'Vắng')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Đặt lúc')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-in lúc')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Hủy lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Bệnh nhân')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='scheduling.scheduleslot', verbose_name='Slot lịch')),
            ],
            options={
                'verbose_name': 'Lịch hẹn',
                'verbose_name_plural': 'Lịch hẹn',
                'db_table': 'booking_appointment',
                'ordering': ['-booked_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndividualBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Họ tên')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='Giới tính')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('id_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='CCCD/CMND')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Lý do khám')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('CHECKED_IN', 'Đã đến quầy'), ('CONVERTED', 'Đã tạo bệnh nhân/lịch hẹn'), ('CANCELLED', 'Hủy'), ('NO_SHOW', 'Vắng')], db_index=True, default='PENDING', max_length=12, verbose_name='Trạng thái')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('source', models.CharField(blank=True, choices=[('WEB_FORM', 'Web form'), ('HOTLINE', 'Hotline'), ('STAFF', 'Nhân viên nhập'), ('QR_OFFLINE', 'QR offline'), ('IMPORT', 'Import'), ('OTHER', 'Khác')], default='OTHER', max_length=20, verbose_name='Nguồn tạo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_individual_booking', to='booking.appointment', verbose_name='Lịch hẹn đã tạo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_individual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_bookings', to='patients.patient', verbose_name='Bệnh nhân đã chuyển đổi')),
                ('schedule_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_bookings', to='scheduling.scheduleslot', verbose_name='Slot lịch')),
            ],
            options={
                'verbose_name': 'Đăng ký khách lẻ',
                'verbose_name_plural': 'Đăng ký khách lẻ',
                'db_table': 'booking_individual_booking',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'booked_at'], name='booking_app_status_ec4550_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['schedule_slot', 'status'], name='booking_app_schedul_f9f19a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='booking_app_patient_ebbf23_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'schedule_slot'), name='uq_booking_appointment_patient_schedule_slot'),
        ),
        migrations.AddIndex(
            model_name='individualbooking',
            index=models.Index(fields=['phone', 'status'], name='booking_ind_phone_8158ae_idx'),
        ),
        migrations.AddIndex(
            model_name='individualbooking',
            index=models.Index(fields=['schedule_slot', 'status'], name='booking_ind_schedul_fb8c49_idx'),
        ),
        migrations.AddIndex(
            model_name='individualbooking',
            index=models.Index(fields=['created_at'], name='booking_ind_created_60be04_idx'),
        ),
        migrations.AddConstraint(
            model_name='individualbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'CHECKED_IN'])), fields=('schedule_slot', 'phone'), name='uq_active_individual_booking_phone_per_slot'),
        ),
    ]
