# Generated by Django 5.2 on 2026-05-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_his_patient_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='HisAppointmentPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Đã xếp hàng'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('SKIPPED', 'Bỏ qua')], db_index=True, default='QUEUED', max_length=10, verbose_name='Trạng thái')),
                ('attempt', models.PositiveSmallIntegerField(default=1, verbose_name='Lần thử')),
                ('endpoint', models.CharField(blank=True, max_length=500, verbose_name='Endpoint')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload gửi đi')),
                ('http_status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Response JSON')),
                ('response_text', models.TextField(blank=True, verbose_name='Response text')),
                ('error', models.TextField(blank=True, verbose_name='Lỗi')),
                ('skipped_reason', models.TextField(blank=True, verbose_name='Lý do bỏ qua')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('pushed_at', models.DateTimeField(blank=True, null=True, verbose_name='Push xong lúc')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='his_push_logs', to='booking.appointment', verbose_name='Lịch hẹn')),
            ],
            options={
                'verbose_name': 'HIS Push Log',
                'verbose_name_plural': 'HIS Push Logs',
                'db_table': 'booking_his_push_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='bk_hislog_status_creat_idx'), models.Index(fields=['appointment', 'created_at'], name='bk_hislog_appt_creat_idx')],
            },
        ),
    ]
