# Generated by Django 5.2 on 2026-03-26 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ma_bn', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('so_cmnd', models.CharField(blank=True, max_length=20, null=True)),
                ('so_bhyt', models.CharField(blank=True, max_length=20, null=True)),
                ('ma_the_bhyt', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='organizations.company')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients_patient',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PatientCompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Company History',
                'verbose_name_plural': 'Patient Company Histories',
                'db_table': 'patients_patientcompanyhistory',
                'ordering': ['-from_date', '-created_at'],
            },
        ),
    ]
