# Generated by Django 5.2 on 2026-04-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_alter_conversation_options_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cuộc hội thoại', 'verbose_name_plural': 'Lịch sử hội thoại'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn', 'verbose_name_plural': 'Tin nhắn'},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='profile',
            field=models.CharField(choices=[('customer', 'Customer Bot'), ('staff', 'Staff Bot'), ('manager', 'Manager Bot')], default='manager', max_length=16, verbose_name='Hồ sơ trợ lý'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.conversation', verbose_name='Hội thoại'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Người dùng'), ('assistant', 'Trợ lý'), ('system', 'Hệ thống')], max_length=16, verbose_name='Vai trò'),
        ),
    ]
