# Generated by Django 5.2 on 2026-03-26 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=8)),
                ('time_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
